# Generated by Django 5.2.3 on 2025-07-01 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapterrole',
            name='role',
        ),
        migrations.AddField(
            model_name='chapterrole',
            name='role_key',
            field=models.CharField(
                choices=[
                    ('reporter_email', 'Reporter (Email Only)'),
                    ('reporter_phone', 'Reporter (Phone Only)'),
                    ('reporter', 'Reporter'),
                    ('manager', 'Manager'),
                    ('owner', 'Owner'),
                ],
                default='assistant',
                max_length=20,
            ),
        ),
    ]
