# Generated by Django 5.2.3 on 2025-07-02 23:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChapterSocialLink',
            new_name='ChapterLink',
        ),
        migrations.RenameModel(
            old_name='HistoricalChapterSocialLink',
            new_name='HistoricalChapterLink',
        ),
        migrations.AlterModelOptions(
            name='historicalchapterlink',
            options={
                'get_latest_by': ('history_date', 'history_id'),
                'ordering': ('-history_date', '-history_id'),
                'verbose_name': 'historical chapter link',
                'verbose_name_plural': 'historical chapter links',
            },
        ),
    ]
