# Generated by Django 5.2.3 on 2025-07-03 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0003_remove_chapterrole_role_chapterrole_role_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapterrole',
            name='role_key',
            field=models.CharField(
                choices=[
                    (None, '---'),
                    ('reporter_email', 'Reporter (Email Only)'),
                    ('reporter_phone', 'Reporter (Phone Only)'),
                    ('reporter', 'Reporter'),
                    ('manager', 'Manager'),
                    ('owner', 'Owner'),
                ],
                max_length=20,
            ),
        ),
    ]
