# Generated by Django 5.2.3 on 2025-07-03 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0003_rename_chaptersociallink_chapterlink_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapterlink',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='historicalchapterlink',
            name='platform',
        ),
        migrations.AddField(
            model_name='chapter',
            name='organizing_hub_url',
            field=models.URLField(blank=True, null=True, verbose_name='Organizing Hub'),
        ),
        migrations.AddField(
            model_name='chapterlink',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalchapter',
            name='organizing_hub_url',
            field=models.URLField(blank=True, null=True, verbose_name='Organizing Hub'),
        ),
        migrations.AddField(
            model_name='historicalchapterlink',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chapterlink',
            name='chapter',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='links',
                to='chapters.chapter',
            ),
        ),
    ]
