# Generated by Django 5.2.3 on 2025-07-10 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0004_remove_chapterlink_platform_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapterlink',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalchapterlink',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
