# Generated by Django 5.2.3 on 2025-07-03 03:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0004_alter_chapterrole_role_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='chapterrole',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        'role_key__in',
                        (
                            'reporter_email',
                            'reporter_phone',
                            'reporter',
                            'manager',
                            'owner',
                        ),
                    )
                ),
                name='valid_role_key_check',
            ),
        ),
    ]
