# Generated by Django 5.2.3 on 2025-07-10 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0005_alter_chapterlink_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterlink',
            name='order',
            field=models.PositiveIntegerField(
                db_index=True, default=0, verbose_name='Order'
            ),
        ),
        migrations.AddField(
            model_name='historicalchapterlink',
            name='order',
            field=models.PositiveIntegerField(
                db_index=True, default=0, verbose_name='Order'
            ),
        ),
    ]
