# Generated by Django 5.2.3 on 2025-07-12 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0006_chapterlink_order_historicalchapterlink_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapterlink',
            options={'ordering': ['order']},
        ),
    ]
