# Generated by Django 5.2.4 on 2025-07-12 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0006_alter_chapterrole_role_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapterrole',
            name='title',
        ),
    ]
