# Generated by Django 5.2.3 on 2025-07-29 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0007_alter_chapterlink_options'),
        ('chapters', '0007_remove_chapterrole_title'),
    ]

    operations = []
