# Generated by Django 5.2.4 on 2025-07-15 00:59

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_historicaluser_email_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='is_staff',
            field=models.BooleanField(
                default=True,
                help_text='Designates whether the user can log into this admin site.',
                verbose_name='staff status',
            ),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='username',
            field=models.CharField(
                db_index=True,
                error_messages={'unique': 'A user with that username already exists.'},
                help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.',
                max_length=150,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name='username',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(
                default=True,
                help_text='Designates whether the user can log into this admin site.',
                verbose_name='staff status',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(
                error_messages={'unique': 'A user with that username already exists.'},
                help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.',
                max_length=150,
                unique=True,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name='username',
            ),
        ),
    ]
