name: docs

on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main
    paths:
      - "docs/**"

jobs:
  check:
    runs-on: ubuntu-latest
    needs: check
    permissions:
      contents: read
    steps:
      - uses: "./.github/shared/build_docs_pages/"
