name: markdown

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths:
      - "**.md"
      - "!docs/**"
  pull_request:
    branches:
      - main
    paths:
      - "**.md"
      - "!docs/**"
  workflow_dispatch:
  workflow_call:
    inputs:
      globs:
        type: string

jobs:
  check_markdown:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
      - name: Configure Globs
        id: globs
        run: |
          GLOBS="${{ github.event.inputs.globs || '''**/*.md'' ''!docs/**/*.md''' }}"
          echo "globs=$GLOBS" >> $GITHUB_OUTPUT
      - uses: DavidAnson/markdownlint-cli2-action@992badcdf24e3b8eb7e87ff9287fe931bcb00c6e # 20.0.0
        with:
          config: ".markdownlint-cli2.jsonc"
          globs: |
            ${{ steps.globs.outputs.globs }}
