# Generated by Django 5.2.4 on 2025-08-07 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0008_merge_20250729_2205'),
        ('members', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='chapter',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)ss',
                to='chapters.chapter',
            ),
        ),
        migrations.AlterField(
            model_name='pendingmember',
            name='chapter',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)ss',
                to='chapters.chapter',
            ),
        ),
    ]
